language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
git:
  depth: 3
cache:
  timeout: 3600
  directories:
  - node_modules
before_install:
  - npm install -g npm
  - npm install -g gulp
script: gulp
after_success:
  - npm run coveralls