language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
git:
  depth: 3
cache:
  timeout: 3600
  directories:
  - node_modules
before_install:
  - npm install -g npm
script: npm test
after_success:
  - npm run coveralls